version: '3.7'

services:
  gorbushka-bot:
    container_name: gorbushka-bot
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - credentials.json:/tmp/credentials.json
    environment:
      - DB_HOST="localhost"
      - DB_PORT="5432"
      - DB_NAME="database"
      - DB_USER="user"
      - DB_PASSWORD="password"
      - BOT_TOKEN="1111111111:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
      - MAIN_CHAT_ID="-1002600610002"
      - PRICE_CHAT_ID="-1002195255275"
      - COMMUNICATION_CHAT_ID="-1002657090671"
      - GOOGLE_CREDENTIALS_JSON_RESOURCE="file:/tmp/credentials.json"
      - CATEGORIES_SPREADSHEET_ID="10PaiJ43qc0ZuYKJyc6Bls4fqFiBzLbMNzktEQ7ExDfo"
      - CATEGORIES_SHEET_NAME="Категории"
      - APPLICATIONS_SPREADSHEET_ID="10PaiJ43qc0ZuYKJyc6Bls4fqFiBzLbMNzktEQ7ExDfo"
      - APPLICATIONS_SHEET_NAME="Заявки"
      - APPROVED_APPLICATIONS_SPREADSHEET_ID="10PaiJ43qc0ZuYKJyc6Bls4fqFiBzLbMNzktEQ7ExDfo"
      - APPROVED_APPLICATIONS_SHEET_NAME="Пользователи"
      - BLACK_LIST_SPREADSHEET_ID="10PaiJ43qc0ZuYKJyc6Bls4fqFiBzLbMNzktEQ7ExDfo"
      - BLACK_LIST_SHEET_NAME="Чёрный список"